export const ciudadEquipo = [
    'Boston',
    'New York',
    'Philadelphia',
    'Toronto',
    'Chicago',
    'Cleveland',
    'Detroit',
    'Indiana',
    'Milwaukee',
    'Atlanta',
    'Charlotte',
    'Miami',
    'Orlando',
    'Washington',
    'Denver',
    'Minnesota',
    'Oklahoma',
    'Portland',
    'Utah',
    'San Francisco',
    'Los Angeles',
    'Phoenix',
    'Sacramento',
    'Dallas',
    'Houston',
    'Memphis',
    'New Orleans',
    'San Antonio'
]